"""baseline: schema as it existed before Alembic was introduced

Hand-authored (not autogenerated) from the live schema of the dev database
-- cross-checked column-by-column via DESCRIBE/SHOW CREATE TABLE against
every one of the 10 tables app/db/models.py declares. Must be applied via
`alembic stamp 0001_baseline` on any environment where these tables already
exist (every current environment); only a genuinely empty database should
ever run this migration's upgrade() for real. See docs/MIGRATIONS.md.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE_KWARGS = {"mysql_engine": "InnoDB", "mysql_charset": "utf8mb4"}


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.UniqueConstraint("email", name="ix_users_email"),
        **_TABLE_KWARGS,
    )
    # Mirrors models.py's `id = Column(Integer, primary_key=True, index=True)`
    # -- a redundant-but-real secondary index on the PK, present in the live
    # schema, so the baseline reproduces it exactly rather than "cleaning it up".
    op.create_index("ix_users_id", "users", ["id"])

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.UniqueConstraint("name", name="name"),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.UniqueConstraint("name", name="name"),
        **_TABLE_KWARGS,
    )

    # No primary key on these two association tables -- matches the live
    # schema exactly (models.py's Table() calls declare neither column as
    # primary_key=True nor any unique constraint). A pre-existing schema
    # wart, deliberately not "fixed" here -- fixing it is a real schema
    # change outside this migration's scope.
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), nullable=True),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), nullable=True),
        sa.Column("permission_id", sa.Integer(), sa.ForeignKey("permissions.id"), nullable=True),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("token", sa.String(length=500), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("token", name="ix_refresh_tokens_token"),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("token_jti", sa.String(length=255), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("token_jti", name="ix_revoked_tokens_token_jti"),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_oauth_provider_account"),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "global_config",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("llm_provider", sa.String(length=50), nullable=True),
        sa.Column("llm_api_key_encrypted", sa.String(length=1000), nullable=True),
        sa.Column("cloud_provider", sa.String(length=50), nullable=True),
        sa.Column("cloud_credentials_encrypted", sa.String(length=4000), nullable=True),
        sa.Column("work_directory", sa.String(length=500), nullable=True),
        sa.Column("data_directory", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        **_TABLE_KWARGS,
    )

    op.create_table(
        "license_keys",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("key", sa.String(length=29), nullable=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=True),
        sa.Column("platform", sa.String(length=20), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_reason", sa.String(length=255), nullable=True),
        sa.UniqueConstraint("key", name="ix_license_keys_key"),
        **_TABLE_KWARGS,
    )
    op.create_index("ix_license_keys_email", "license_keys", ["email"])


def downgrade() -> None:
    # NEVER run against an environment with real data -- drops every
    # original auth table. Exists solely so tests/test_migrations.py can
    # exercise a full upgrade/downgrade cycle against a throwaway database.
    op.drop_table("license_keys")
    op.drop_table("global_config")
    op.drop_table("oauth_accounts")
    op.drop_table("revoked_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("role_permissions")
    op.drop_table("user_roles")
    op.drop_table("permissions")
    op.drop_table("roles")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
