from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Ensure app/ is importable when alembic is invoked from the repo root
# (alembic.ini sets prepend_sys_path = . for this).
from app.core.config import settings
from app.db.base import Base

# Imported for its side effect of registering every ORM model class onto
# Base.metadata, so target_metadata below is complete. As of this revision
# no models exist yet for the new multi-tenant tables (0001/0002 are
# hand-written, not autogenerated) -- this import matters for whichever
# future revision starts using --autogenerate.
import app.db.models  # noqa: F401,E402

# this is the Alembic Config object, which provides access to values within
# the .ini file in use.
config = context.config

# Drive the connection from the same settings the running app uses, rather
# than a URL hardcoded in alembic.ini -- keeps migrations and the app
# permanently pointed at the same database with no separate config to drift.
# Only applied as a fallback: if a caller has already set sqlalchemy.url on
# this Config object (tests/test_migrations.py does this to point migrations
# at an isolated throwaway database), that value wins -- real `alembic`
# CLI usage never sets it, so this is a no-op for normal operation.
if not config.get_main_option("sqlalchemy.url"):
    config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Interpret the config file for Python logging. disable_existing_loggers
# defaults to True, which silently disables (permanently, for the rest of
# the process -- not just during this call) every logger not explicitly
# listed in alembic.ini's [loggers] section, including every application
# logger the app itself creates (e.g. permission_parity.py's). Explicit
# False here to avoid that footgun -- discovered when running the test
# suite: tests/test_migrations.py invoking Alembic commands was silently
# disabling tests/test_permission_parity.py's caplog-based assertions
# whenever it ran first in the same session.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Emits SQL to stdout instead of executing against a live connection --
    useful for `alembic upgrade head --sql` review before applying anything
    for real (see docs/MIGRATIONS.md verification steps).
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode, against a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
